### ISSUE TITLE
Cursor focused at the end of the file

### ISSUE THREAD

**Issue by sdolard** [sindresorhus/atom-editorconfig#51] opened 2015-09-10 07:13 UTC
Hi, 

Since 1.2.0, when we try to open a file at a defined line number, the cursor is set to the end of the file, not on the correct line.

The file must not have been opened before.

![optimised](https://cloud.githubusercontent.com/assets/165201/9782247/fbbd5c7e-579b-11e5-892e-76865b552525.gif)

**Comment by sebflipper** [comment] 2015-09-15 12:24
I get this problem as well, in a slightly different way, but I think it's related to the same issue.

Steps to reproduce:
1. install `atom-editorconfig`
2. Press `cmd+shift+f` (or search project) and search for a known word (in a large file, which requires scrolling)
3. Click a search result
4. Cursor is focused at the end of the file

What should happen:
* Cursor should be focused on selected search result

**Comment by noseglid** [comment] 2015-09-15 14:27
I get the same thing, but when using symbols-view's go-to-declaration (only when the file isn't currently opened). Seems very similar to what's reported in here.

**Comment by adambuczynski** [comment] 2015-09-16 19:41
Same thing going on for me, see https://github.com/atom/find-and-replace/issues/526

I've narrowed it down to the problem coming from this atom package. Will have to disable the package for the time being, as it's unworkable at the moment.

**Comment by caleb** [comment] 2015-09-17 01:38
I've run into this as well. This was the last plugin I thought would be causing the issue :) I haven't had a chance to look into what's causing it yet, but I might this weekend.

**Comment by xdumaine** [comment] 2015-09-21 14:47
+1

**Comment by g1smo** [comment] 2015-09-22 11:34
This is a problem for me, too.

**Comment by sdornan** [comment] 2015-10-02 19:45
+1

**Comment by andersryanc** [comment] 2015-10-06 20:37
+1
Experiencing this as well (using 1.2.0). As mentioned above, it seems to have started happening when the end_of_line support got added in, and seems to be fixed by removing the end_of_line setting from my .editorconfig file.

**Comment by eburi** [comment] 2015-10-10 15:25
+1, closed the issue on the atom-project when I found out that it is related to the editorconfig-package

**Comment by varemenos** [comment] 2015-10-16 19:14
:+1:

**Comment by sindresorhus** [comment] 2015-10-27 09:07
@caleb Mind doing a PR with your fix?

**Comment by qiushihe** [comment] 2015-10-30 19:11
@sindresorhus couldn't you just take what's in this comment https://github.com/sindresorhus/atom-editorconfig/issues/51#issuecomment-140940459, and see if it works and/or breaks anything, and if everything looks good just apply the update? @caleb's comment is from more the a month ago, surely we all have commitments IRL, the longer this bug continues to exist the longer everyone have to either: be annoyed by this bug; or not use this package at all.

**Comment by sindresorhus** [comment] 2015-10-31 09:12
> couldn't you just take what's in this comment #51 (comment), and see if it works and/or breaks anything

So could you... This is open source. Complaining will get you nowhere. If something bothers you, fix it.

> surely we all have commitments IRL

And I don't?

> the longer this bug continues to exist the longer everyone have to either: be annoyed by this bug

Seeing how nobody has done a PR yet, it can't be very annoying.

> or not use this package at all.

Yes, please do.

**Closed by sindresorhus** 2015-10-31 09:12 UTC
Labels: bug
