### ISSUE TITLE
Updates to `.editorconfig` don't update open files

### ISSUE THREAD

**Issue by erikdonohoo** [sindresorhus/atom-editorconfig#13] opened 2014-07-18 14:53 UTC
Files need to be closed and reopened for changes to the `.editorconfig` to be noticed.

The file should be watched and then refresh any currently open files to show the changes.

**Comment by sindresorhus** [comment] 2015-06-28 01:03
Sure. PR welcome.

**Comment by cemrich** [comment] 2015-10-31 10:00
There is a [fs.watch() function](https://nodejs.org/api/all.html#all_fs_watch_filename_options_listener) that could be used. 
The problem is we don't know the exact files the config rules are parsed from. In most cases it will be `.editorconfig` on root level but there could be more config files in subdirectories as well. 
Searching for this files could be expensive (however, that's just an assumption) - especially when handling deeply nested `node_modules` directories.

**Comment by florianb** [comment] 2016-04-01 08:26
We could try to watch all involved files, if one file changes the config is resembled and set.

**Comment by florianb** [comment] 2016-04-29 20:12
This feature will be implemented with the next (and first) feature-milestone. I will close this issue in favor of the more technical discussion in #85 - please feel free to follow up and participate!

Thank you all for contributing! 💝

**Closed by florianb** 2016-04-29 20:12 UTC
Labels: enhancement, help wanted
