### ISSUE TITLE
Deprecated selector in `editorconfig\styles\atom-editorconfig.less`

### ISSUE THREAD

**Issue by sbistrovic** [sindresorhus/atom-editorconfig#145] opened 2016-11-10 09:55 UTC
In `editorconfig\styles\atom-editorconfig.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .ecfg-wrap-guide` => `atom-text-editor.editor .ecfg-wrap-guide`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by florianb** [comment] 2016-11-10 10:30
Thanks 💝  -- this is a duplicate of #144

**Closed by florianb** 2016-11-10 10:30 UTC

**Comment by sbistrovic** [comment] 2016-11-10 10:32
:thumbsup:
