### ISSUE TITLE
Use the `atom-text-editor` tag instead of the `editor` class.

### ISSUE THREAD

**Issue by leonardosouza** [sindresorhus/atom-editorconfig#162] opened 2016-11-25 11:26 UTC
In styles/atom-editorconfig.less: Use the `atom-text-editor` tag instead of the `editor` class.

**Comment by florianb** [comment] 2016-11-25 14:34
Thanks for reporting, this is a dupe of #160

**Closed by florianb** 2016-11-25 14:34 UTC
