### ISSUE TITLE
.editorconfig not working as intended - softTabs looks like it's being set, but isn't

### ISSUE THREAD

**Issue by mven** [sindresorhus/atom-editorconfig#70] opened 2016-03-22 20:36 UTC
My .editorconfig wasn't properly working on Atom (works on Sublime Text), so I wanted to try to debug what could be causing the issue.

From what I gathered it looked like the everything was working fine. Logging the TextEditor object shows that this package *looks* like it's setting the correct properties, but for some reason Atom itself isn't recognizing the change and shows some discrepancies inside the object:

![screen shot 2016-03-22 at 3 20 41 pm](https://cloud.githubusercontent.com/assets/940113/13966958/c60eafa2-f042-11e5-8a9d-99194ece0d01.png)

Running the `getSoftTabs()` method in the console returns a false:

![screen shot 2016-03-22 at 3 21 27 pm](https://cloud.githubusercontent.com/assets/940113/13967044/4210d7f6-f043-11e5-88d9-e14ecb3e167f.png)

I was able to enable soft tabs through the console, if I did a `atom.workspace.getActiveTextEditor().setSoftTabs(true);`

![screen shot 2016-03-22 at 3 33 12 pm](https://cloud.githubusercontent.com/assets/940113/13967083/6d31e8d0-f043-11e5-9c03-8e0ac41b3f98.png)

Not sure how to fix this though. This looks like an Atom bug. Any thoughts?

**Comment by florianb** [comment] 2016-04-01 07:44
Hi @mven - thank you very much for that report! :candy:

In my experience the Atom-platform can be considered as fairly stable.

I could imagine that this issue may be caused by a wrong sequence of events, namely the softtabs-setting may be overwritten after the editorconfig-package initially set it right. We have to do further investigations on this, if possible i will pick this issue up for the upcoming patch-release!

**Comment by florianb** [comment] 2016-04-08 19:40
I have currently exactly the same issue.

**Comment by florianb** [comment] 2016-04-10 11:42
Okay @mven - i guess i figured this one out. Editorconfig seems only working properly if the Core-Setting "Tab Type" of your Editor is set to "auto".

If this setting is set to any specific value, it overrides the editorconfig-changes in the last second. 😁 

Please do me the favor to verify that finding! 🙏

So how going on with this. I can currently imagine two Options:

- Inform the User with a Info-Notification (probably also offering to fix the setting)
- Leave a "Warning" in the console (which will probably be seen if a user starts searching for the fault)

**Comment by florianb** [comment] 2016-04-11 07:46
I am sorry, i made a mistake - unfortunately my previous answer is not solving the problem. I do further investigations. I beg your pardon for the noise.

**Comment by florianb** [comment] 2016-04-11 10:40
Okay it seems i finally got to the ground of the problem, which is a call of [TextEditor.handleTokenization](https://github.com/atom/atom/blob/v1.6.2/src/text-editor.coffee#L3120) being invoked by the displayBuffer. This overrides the Tab-settings. Since i couldn't figure out when this is being invoked and how to prevent it, i decided to override it as a first patch.

So this behavior is now confirmed and pinned down by specs (in the draft https://github.com/florianb/atom-editorconfig/tree/iss70).

I guess this will need a fix in the TextEditor-implementation - until this has be done i will block the handleTokenization-function to keep this issue fixed.

**Comment by florianb** [comment] 2016-04-12 08:46
This bug is issue seems to be part of a more complex malfunction. I move its solution into a separate issue #81 and therefore close this issue. I'd appreciate if follow that issue, too.

Thanks for your patience. ☕

**Closed by florianb** 2016-04-12 08:46 UTC
Labels: bug

**Comment by mven** [comment] 2016-04-15 02:49
Great, thanks. I'll follow that issue.
