### ISSUE TITLE
Force Unix-style newlines in windows 10

### ISSUE THREAD

**Issue by marcelocarmona** [sindresorhus/atom-editorconfig#96] opened 2016-07-11 04:23 UTC
I'd like you to take a look on the following unexpected behavior.

When I create a newline, the end of the line is CRLF instead of LF.
My .editorconfig have a  **end_of_line = lf**

### versions
**Atom version**: 1.8.0
**System**: Windows 10, version 1511

### list of installed packages

Built-in Atom Packages (89)
├── about@1.5.0
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.2
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.39.0
├── bracket-matcher@0.82.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.38.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.0.5
├── git-diff@1.0.1
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.3
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.1
├── language-css@0.36.1
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.21.1
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.34.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.1
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.1
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.2
├── line-ending-selector@0.4.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.1
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.1
├── open-on-github@1.0.1
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.2.3
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.96.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (18) C:\Users\Agencia EGO\.atom\packages
├── api-workbench@0.8.33
├── atom-beautify@0.29.9
├── atom-soda-dark-ui@1.1.0
├── atom-webbrowser@2.1.4
├── browser-plus@0.0.67
├── docblockr@0.7.3
├── editorconfig@1.4.1
├── file-icons@1.7.16
├── git-plus@5.16.2
├── linter@1.11.14
├── linter-eslint@7.2.4
├── linter-sass-lint@1.6.1
├── merge-conflicts@1.4.4
├── minimap@4.24.7
├── platformio-ide-terminal@2.1.0
├── react@0.15.0
├── sync-settings@0.7.2
└── todo-show@1.6.0

### my `.editorconfig`

> root = true
> 
> [*]
> charset = utf-8
> end_of_line = lf
> insert_final_newline = true
> trim_trailing_whitespace = true
> 
> [*.{js,html,css,styl,scss}]
> indent_style = space
> indent_size = 2
> 
> [*.md]
> indent_style = space
> indent_size = 4
> trim_trailing_whitespace = false

**Comment by florianb** [comment] 2016-07-18 07:59
Hi @mclo -- thanks for getting in touch!

I'm sorry to hear atom-editorconfig is not working as expected.

Does the file only contain your preferred line-endings? You may face inconsistencies if you "change" the line endings through editorconfig if the given file was formatted using another line ending in first place.

**Comment by dlebedynskyi** [comment] 2016-08-02 17:15
Having same issue. editorconfig has LF. 
Atom  has line-ending-selector default package. It has - Os default. Editorconfig is completely ignored. 
you can change default to LF there. But even if you put crlf in editorconfig - LF still will be used. 
It looks like default package override editorconfig

**Comment by florianb** [comment] 2016-08-03 07:20
Hi @dlebedynskyi - thanks for getting in touch. Could you please check if the file you're editing is consistently being formatted with the line-endings you're finally want to use?

**Comment by dlebedynskyi** [comment] 2016-08-04 21:27
@florianb it does not look like it is constantly changing. But even with  line-ending-selector default to LF, all new fles come with CRLF still.

**Comment by Clijsters** [comment] 2016-08-05 21:38
Windows 7 here and same issue.
(Only files which came already with `lf` as ending keep its default.)

**Comment by florianb** [comment] 2016-08-06 08:37
@dlebedynskyi @Clijsters - Atom guesses the linendings based upon which linenendings already exist in the file and then overrides the settings of atom-editorconfig. So if there exist any non-conforming linenedings (to the editorconfig) it is normal behavior that Atom changes the line endings and it is very difficult to change that behavior.

If you can be sure, that a file already contains only desired line endings (as defined in the editorconfig) and Atom still changes the line endings - that is a bug.

I then need a copy of the file you're starting with, your editorconfig-files used in that project and a list of the activated packages.

I am really sorry that i don't have an easy answer to this issue.

**Comment by dlebedynskyi** [comment] 2016-08-09 14:16
@florianb  Thank you for explanation. 
so far I checked that a new file is created with LF as expected. I'll keep watching if I see what could this bug. But it could we not a bug at all after you explained how atom works. Thanks

**Comment by florianb** [comment] 2016-10-05 07:37
I close this issue in favor of #89 -- feel free to get in touch if there is anything you'd like to add. Thanks everybody!

**Closed by florianb** 2016-10-05 07:37 UTC
Labels: on hold
