### ISSUE TITLE
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

### ISSUE THREAD

**Issue by leonardosouza** [sindresorhus/atom-editorconfig#161] opened 2016-11-25 11:26 UTC
In styles/atom-editorconfig.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

**Comment by florianb** [comment] 2016-11-25 14:34
Thanks for reporting, this is a dupe of #160

**Closed by florianb** 2016-11-25 14:34 UTC
