### ISSUE TITLE
Unmaintained

### ISSUE THREAD

**Issue by florianb** [sindresorhus/atom-editorconfig#231] opened 2018-12-10 10:26 UTC
# Atom-Editorconfig is now Unmaintained

First of all - sorry for everybody coming here because of any issues thrown by the package. Take the opportunity and repair it if you'd like to use it.

### Why am i dropping maintenance?

I am not using Atom as my main editor anymore. One reason is i started disliking Atom as a platform for plugin-developers. When it started it was announced as the "hackable" Editor you can use to do anything you want.

I feel in fact, that the Atom API lacks of two very important points to be able to rely on: transparency and stability.
It happened more than once, that we had to react on changes in the API which were announced but introduced breaking changes without any assistance in adoption. These reoccurring changes just created efforts on a timely base which consumed a big amount of my motivation since we were just catching up.
On the other hand the whole API is badly documented for plugin-developers. There is no stability-indicator which would help to rely on "stable" functions. The API-team missed the opportunity to create a good abstraction for the plugin-API everything may change whenever they decide to do something. This plugin also relies on "unofficial" methods which are considered as maybe changing (which didn't happen for years) to hack around some basic limitations of the editor's implementation.
They also decided to force their own implementation of source-formatting (based on mime-types rather then file endings) which blocks some functionality of editorconfig and removes the ability to change some needed properties for the text-buffers.

As you might guess i'm not getting paid to work on this package and i feel like i spend a lot of time fixing functionality which would still work if the API wouldn't have changed that drasticallly.

### But I need Editorconfig in Atom!

Take action - you can fix it. If you're Atom on a daily basis and you're firm with JS, give it a try! I will stay here and answer questions about design-decisions.

Farewell.

P.s.: The state of my experimental rewrite can be seen here: https://github.com/florianb/atom-editorconfig/tree/rewrite

**Comment by Alhadis** [comment] 2018-12-24 15:54
I can do it.

**Comment by florianb** [comment] 2018-12-28 08:58
I am happy to hear that @alhadis - thanks for weighing in.

@sindresorhus may consider adding you as maintainer.

**Comment by sindresorhus** [comment] 2018-12-28 11:39
Awesome! Added you, @Alhadis.

I'm gonna keep this issue open until `atom-editorconfig` is in a better and working shape. We could always use more contributors and maintainers.

**Comment by Alhadis** [comment] 2018-12-28 11:49
Not a problem. 👍 Will look at fixing some outstanding issues after the holidays, starting with the trailing-line bug (which is what I came here to report).

**Comment by sindresorhus** [comment] 2018-12-28 11:55
I would also try to prioritize getting the open PRs merged or closed.

**Comment by the-j0k3r** [comment] 2019-02-13 06:36
Various fixes and improvements have gone in since 2.2.2 now a year old release

Please consider making a new release sooner rather than later. @sindresorhus @florianb

**Comment by Alhadis** [comment] 2019-02-13 08:20
Shit, sorry it's taken so long to get back to this. 😞

Will try to cut an emergency release for this and #232 ASAFP.

**Comment by Arcanemagus** [comment] 2019-02-13 08:22
I would _highly_ recommend getting [`@semantic-release/apm-config`](https://github.com/semantic-release/apm-config) configured, it has the downside of all commits (that you want to trigger a build) needing to follow a standard... but the major upside that as soon as you make any commit or merge something to `master` that should trigger a release, it's done automatically.

**Comment by Alhadis** [comment] 2019-02-13 08:25
That can wait until we've lifted this package out of hot water, fixed the regression tests, and have a codebase in better shape before concerning ourselves about ancillary elements.

**Comment by florianb** [comment] 2020-01-06 09:53
@Alhadis you're doing great work and thank you for your efforts - i guess we can close this issue? It would probably be a good idea to create "Searching for Contributors"-issue?

**Comment by Alhadis** [comment] 2020-01-06 10:10
@florianb Possibly. I was hesitant to close this issue because I felt it was @sindresorhus's prerogative, rather than mine.

**Comment by sindresorhus** [comment] 2020-01-06 10:18
I think I just forgot to do so. Thanks for all your work @Alhadis 🙌

**Closed by sindresorhus** 2020-01-06 10:18 UTC
