### ISSUE TITLE
Not working on JS files

### ISSUE THREAD

**Issue by FezVrasta** [sindresorhus/atom-editorconfig#103] opened 2016-10-17 13:29 UTC
I have EVERYTHING set to auto, but it still doesn't work on JavaScript files.

To note that I have `language-babel` installed, but its tabs settings are set to auto as well...
It has no effect neither if I manually specify the tabs length on the EditorConfig plugin settings.

```
$ apm --version
apm  1.12.5
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.10.0
$ atom --version
Atom    : 1.11.1
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ apm list
Built-in Atom Packages (89)
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.52.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.44.0
├── base16-tomorrow-dark-theme@1.2.0
├── base16-tomorrow-light-theme@1.2.0
├── one-dark-ui@1.6.0
├── one-light-ui@1.6.0
├── one-dark-syntax@1.3.0
├── one-light-syntax@1.3.0
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── about@1.7.0
├── archive-view@0.61.1
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.2
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.1
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.1
├── bookmarks@0.42.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.40.0
├── find-and-replace@0.201.1
├── fuzzy-finder@1.4.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.2
├── image-view@0.59.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@1.0.0
├── notifications@0.65.1
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.242.2
├── snippets@1.0.2
├── spell-check@0.68.2
├── status-bar@1.4.1
├── styleguide@0.47.0
├── symbols-view@0.113.1
├── tabs@0.101.0
├── timecop@0.33.2
├── tree-view@0.209.3
├── update-package-dependencies@0.10.0
├── welcome@0.35.1
├── whitespace@0.33.0
├── wrap-guide@0.38.2
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.2
├── language-csharp@0.12.1
├── language-css@0.37.1
├── language-gfm@0.88.0
├── language-git@0.15.0
├── language-go@0.42.1
├── language-html@0.45.1
├── language-hyperlink@0.16.0
├── language-java@0.23.0
├── language-javascript@0.119.0
├── language-json@0.18.2
├── language-less@0.29.5
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.2
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.69.0
├── language-ruby-on-rails@0.25.0
├── language-sass@0.56.0
├── language-shellscript@0.22.4
├── language-source@0.9.0
├── language-sql@0.23.0
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.9
└── language-yaml@0.26.0

Community Packages (39) /Users/federicozivolo/.atom/packages
├── Stylus@3.1.0
├── auto-indent@0.5.0
├── auto-update-packages@1.0.1
├── br4ckets-light@1.0.0
├── chrome-color-picker@0.8.0
├── close-on-left@0.6.1
├── dash@1.7.0
├── dot-hide@1.5.0
├── duotone-dark-sea-syntax@1.0.0
├── duotone-dark-space-syntax@1.0.0
├── duotone-dark-syntax@1.0.0
├── editorconfig@1.4.1
├── flex-tool-bar@0.11.0
├── git-blame@0.4.11
├── git-control@0.8.2
├── git-diff-details@1.3.0
├── git-plus@5.18.0
├── git-time-machine@1.5.3
├── highlight-selected@0.11.2
├── language-babel@2.44.1
├── language-jade@0.7.2
├── language-postcss@1.3.0
├── language-stylus@0.2.0
├── less-than-slash@0.16.0
├── line-diff-details@1.4.0
├── linter@1.11.18
├── linter-eslint@8.0.0
├── linter-jshint@3.0.1
├── markdown-table-formatter@2.8.3
├── open-project-in-tower@1.4.0
├── open-recent@5.0.0
├── open-terminal-here@2.1.4
├── project-viewer@0.3.25
├── seafoam-syntax@2.2.0
├── smart-tab-name@1.0.5
├── sync-settings@0.7.2
├── synced-sidebar@0.4.3
├── tool-bar@1.0.1
└── untitled-no-more@0.1.0

└── (empty)

```

```
# EditorConfig is awesome (when it works): http://EditorConfig.org


# top-most EditorConfig file
root = true

# Common rules to all files
[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
```

**Comment by florianb** [comment] 2016-10-17 13:32
Please add the file-tree of the misbehaving files (f.e. with `tree -a .`).

**Comment by FezVrasta** [comment] 2016-10-17 13:40
.editorconfig
test.js

```
// test.js

// Link.react-test.js
import React from 'react';
import Link from '../Link.react';
import renderer from 'react-test-renderer';

test('Link changes the class when hovered', () => {
  const component = renderer.create(
    <Link page="http://www.facebook.com">Facebook</Link>
  );
  let tree = component.toJSON();
  expect(tree).toMatchSnapshot();

  // manually trigger the callback
  tree.props.onMouseEnter();
  // re-rendering
  tree = component.toJSON();
  expect(tree).toMatchSnapshot();

  // manually trigger the callback
  tree.props.onMouseLeave();
  // re-rendering
  tree = component.toJSON();
  expect(tree).toMatchSnapshot();
});
```

**Comment by florianb** [comment] 2016-10-17 13:50
Looks good to me. But as a clarification, editorconfig does not reformat your file (especially preceeding whitespaces). So if you append new lines to this file (by hand) and you're f.e. pressing tab you should expect the indentation you configured in the editorconfig file.

However, there is a known issue, where Atom tries to derive the "right" indentation from already existing lines. Atom might -- due to this issue -- override the editorconfig-settings, if the file is not entirely formatted the expected way.

In your case i'd advise you to reformat your file according to your settings (`s/  /    /`), editorconfig should then ensure future edits won't break your formatting rules.

**Comment by FezVrasta** [comment] 2016-10-17 13:51
I see... Formatting it manually fixed the problem. There should be a FAQ section with all these quirks I guess.

**Comment by FezVrasta** [comment] 2016-10-17 16:18
Ok I'm having the same problem again, this time even if everything is indented with 4 spaces, Atom sets the indentation to 2...

This extension seems completely broken to me.

**Comment by florianb** [comment] 2016-10-18 07:13
I am sorry, i cannot reproduce your issue.

It might be that another package prevents the persistence of our indentation length-setting. I hope we address this with the next minor-release.

You can leave this issue open if you would like us to come back to this issue after the next release. Otherwise i will close it.

**Closed** 2016-10-20 12:40 UTC

**Comment by FezVrasta** [comment] 2016-10-21 14:40
Still having the problem after the update...

![image](https://cloud.githubusercontent.com/assets/5382443/19602287/01a49e16-97ad-11e6-9cae-fe574b69064d.png)

**Comment by FezVrasta** [comment] 2016-10-21 14:41
Noticed that after I paste some content with the wrong indentation I have to close and re-open the file to see the indentation properly working.
