### ISSUE TITLE
Opening files automatically registers a change

### ISSUE THREAD

**Issue by simon-ls** [sindresorhus/atom-editorconfig#69] opened 2016-03-18 10:10 UTC
When you open any file with editorconfig enabled, Atom registers a change to the file instantly. As well as being quite annoying, it makes it difficult to track what you have and haven't made changes to, When asked if I want to save my changes, I'm not always sure that I have changed anything, or if it's just editorconfig.

**Comment by Arcanemagus** [comment] 2016-03-18 16:15
This shouldn't be happening, are you absolutely sure `editorconfig` isn't actually making a change? Most likely it is fixing something that you may not be showing, such as line endings.

**Comment by glen-84** [comment] 2016-03-25 12:44
See https://github.com/editorconfig/editorconfig/issues/248

**Comment by simon-ls** [comment] 2016-03-29 08:03
@glen-84 You're right. This is a duplicate of #248

**Comment by florianb** [comment] 2016-04-01 07:53
Hi @simon-ls - thanks for reporting! :candy: 

Unfortunately the current implementation is faulty in a sense where it let Atom behave unexpected (changing files, breaking the behavior of other plugins). It is difficult to fix it because we have to exactly examine how Atom behaves on buffer-changes behind the curtain (like replacing line-endings).

We will try to figure out how to fix that - i beg for patience.

**Comment by florianb** [comment] 2016-04-02 10:13
This issue is caused by https://github.com/sindresorhus/atom-editorconfig/blob/master/index.js#L45 which always reformats the line endings if the corresponding config-setting exists.

I guess this *change* marks the buffer always as changed, even if no line endings were replaced.

To avoid this we should check first, if there are any wrong line endings in the document.

**Comment by sindresorhus** [comment] 2016-04-02 10:52
@florianb I would rather argue it's an Atom bug. It shouldn't mark the buffer as changed if nothing changed.

**Comment by glen-84** [comment] 2016-04-02 14:28
Would it be difficult to change this entirely, and have the transformations applied on file save instead (as it should be)?

**Comment by florianb** [comment] 2016-04-03 18:42
Good point @sindresorhus, i guess i would try to expose this issue to the Atom-team. I then would implement the check as a quick-fix, since i expect that it will at least take some time to get that feature into Atom. (As far as i can oversee the upcoming changes i expect some other Atom-API-changes, too, in order to make Atom truly editorconfig-ready).

**Comment by sindresorhus** [comment] 2016-04-03 18:44
@florianb Yup. I'm good with that.

Cross-link any Atom issue you open for future reference.

**Comment by florianb** [comment] 2016-04-03 18:55
@glen-84 interesting, where did you get it should be applied on file saving? As far as i understood editorconfig until now - i expected it would set my editor-configuration properly and would **not** change any files directly.

Unfortunately editorconfig seems to be not very strict. And since its currently implemeted that way, i guess we stick with it for the beginning, to avoid unexpected behavior for current users.

**Comment by glen-84** [comment] 2016-04-03 19:56
@florianb I linked to it earlier: [Should settings be applied when you open a file (or when you save it)?](https://github.com/editorconfig/editorconfig/issues/248)

IMHO, the current behaviour is unexpected – just because I open a file, doesn't mean that I want to make any changes to it.

**Comment by florianb** [comment] 2016-04-04 07:20
I treat the current handling of line endings as temporary **workaround** since the API of Atom lacks of proper config-possibilities. This workaround will hopefully be fixed in the future.

However - i treat changing something in the document at file saving as even worse than at the beginning, since this may introduce unexpected behavior in the whole technology stack. As developer i expect to leave a file as it is when i save it.

**Comment by florianb** [comment] 2016-04-05 11:22
:memo: linendnings should probably be set via (yet undocumented functions) `set/getPreferredLineEndings`: https://github.com/atom/text-buffer/blob/v8.2.1/src/text-buffer.coffee#L418

**Comment by florianb** [comment] 2016-04-08 14:17
Okay in first tests i could not verify the described behavior. I would like to ask you @simon-ls to give me some more information:

- [ ] is the issue still present?
- [ ] which OS do you use?
- [ ] which version of Atom & editorconfig do you use?
- [ ] does the issue pop up on every file-activity?
- [ ] please post the involved `.editorconfig`, as well as the directory-structure of the suspected files.

Thank you very much! :beer:

However - du to the current examination i found out, that the whole line_endings-treatment may be improved. I will file that as enhancement, being handled in a different issue.

**Comment by simon-ls** [comment] 2016-04-08 14:55
Hey @florianb  

- Yes
- Windows 10
- Atom 1.6.2 with editorconfig 1.2.4
- The issue occurs upon opening a file. Say I open a file, I make no changes, then decide to close it, Atom asks if I'd like to save changes, despite the fact that I haven't changed a single line or character.
- I'm using default editorconfig settings

**Comment by florianb** [comment] 2016-04-08 14:57
@simon-ls - thank you very much! This is very helpful and makes it more complicated. I beg for more patience.. :smiley_cat:

**Comment by florianb** [comment] 2016-04-08 16:07
Hmm - i will try to reproduce that behavior. I have the strong feeling that the file you are opening has different line_endings than the editorconfig-settings dictate. :thought_balloon:

**Comment by glen-84** [comment] 2016-04-08 16:28
@florianb,

I was just about to suggest the same thing. I've seen the same thing before, and in fact it's the reason why I initially posted that question to the EditorConfig repo.

> As developer i expect to leave a file as it is when i save it.

As a developer I expect to be able to open and browse files without any changes being made. Actually, in this case, the extension should not be changing the whole file at all – it should only be changing a setting (the EOL setting). I have no idea whether or not the Atom APIs support this though.

**Comment by florianb** [comment] 2016-04-08 16:28
Ha! I was able to track it down, it's like i assumed. You may expect a patch soon.

**Closed** 2016-04-10 09:55 UTC
Labels: bug
